"""사이드바 렌더링 모듈."""

from __future__ import annotations

from datetime import datetime

import pandas as pd
import streamlit as st

from core.callbacks import cb_load_file, cb_reset_data, cb_rollback, cb_rescan


def _build_report_txt(audit_log: list[str], metrics: dict) -> str:
    """audit_log와 최종 메트릭을 합쳐 TXT 리포트 문자열을 반환한다."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    score = metrics["score"]
    grade = "우수" if score >= 80 else ("보통" if score >= 60 else "위험")

    lines = [
        "=" * 62,
        "  PureSet  데이터 정제 이력 리포트",
        f"  생성 일시 : {now}",
        "=" * 62,
        "",
        "■ 최종 데이터 신뢰도",
        f"  신뢰도 스코어  : {score:.1f}점  [{grade}]",
        f"  전체 행 수     : {metrics['n_total']:,}건",
        f"  결측치         : {metrics['n_missing']:,}건  ({metrics['r_missing'] * 100:.1f}%)",
        f"  중복 행        : {metrics['n_duplicated']:,}건  ({metrics['r_dup'] * 100:.1f}%)",
        f"  이상치         : {metrics['n_outlier']:,}건  ({metrics['r_outlier'] * 100:.1f}%)",
        "",
        "■ 정제 작업 이력",
    ]

    for i, entry in enumerate(audit_log, 1):
        lines.append(f"  {i:02d}. {entry}")

    lines += [
        "",
        "=" * 62,
        "  Generated by PureSet — B2B 데이터 신뢰도 진단 & 자동 교정",
        "=" * 62,
    ]
    return "\n".join(lines)


def render_sidebar(df: pd.DataFrame | None, metrics: dict | None = None) -> None:
    with st.sidebar:
        # ── 로고 ─────────────────────────────────────────────────
        st.markdown(
            """
            <div style="text-align:center;padding:1.2rem 0 0.5rem;">
                <span style="font-size:2.4rem;">🔬</span>
                <h2 style="margin:0.2rem 0 0;color:#1E40AF;font-weight:900;
                           letter-spacing:-1px;font-size:1.8rem;">PureSet</h2>
                <p style="margin:0;color:#6B7280;font-size:0.78rem;line-height:1.4;">
                    B2B 데이터 신뢰도 진단 &amp; 자동 교정
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.divider()

        # ── 파일 업로드 ───────────────────────────────────────────
        st.markdown("**📂 데이터 불러오기**")

        st.file_uploader(
            "CSV 또는 Excel 파일 업로드",
            type=["csv", "xlsx", "xls"],
            key="_uploaded_file",
            on_change=cb_load_file,
            help="업로드 즉시 현재 데이터를 교체합니다. UTF-8 / EUC-KR / Excel 모두 지원. 문자열 컬럼 자동 인코딩.",
        )

        err = st.session_state.get("_upload_error")
        if err:
            st.error(err, icon="🚨")

        if df is not None and st.session_state.get("_uploaded_file") is not None:
            numeric_cols = df.select_dtypes(include="number").columns.tolist()
            object_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
            enc_note = f" · 문자열 {len(object_cols)}개 자동 인코딩" if object_cols else ""
            col_preview = ", ".join(numeric_cols[:4]) + (" 외..." if len(numeric_cols) > 4 else "")
            st.success(
                f"✅ {len(df):,}행 · {len(df.columns)}컬럼 로드됨{enc_note}  \n"
                + (f"수치형: {col_preview}" if numeric_cols else "수치형 컬럼 없음 (문자열만 구성)"),
            )

        st.divider()

        # ── 데이터 관리 ───────────────────────────────────────────
        st.markdown("**🗂️ 데이터 관리**")

        st.button(
            "🔄  가상 데이터로 초기화",
            on_click=cb_reset_data,
            use_container_width=True,
            help="내장 더미 데이터(사인파 + 이상 주입)를 새로 생성합니다.",
        )

        history_len = len(st.session_state.get("history", []))
        has_history = history_len > 0

        st.button(
            f"🚨  롤백" + (f" ({history_len}단계)" if has_history else " (내역 없음)"),
            on_click=cb_rollback,
            disabled=not has_history,
            use_container_width=True,
            help="마지막 변경 직전 상태로 되돌립니다. 롤백 이벤트도 정제 이력에 기록됩니다.",
        )

        st.divider()

        # ── 이상치 분석 ───────────────────────────────────────────
        st.markdown("**🔍 이상치 분석**")
        st.caption(
            "수정 후 이상치는 자동 재탐지되지 않습니다.  \n"
            "정제 완료 후 아래 버튼으로 최종 재분석하세요."
        )
        st.button(
            "🔍  이상치 재스캔",
            on_click=cb_rescan,
            use_container_width=True,
            type="primary",
            help="IsolationForest를 재실행하여 현재 데이터의 이상치를 새로 탐지합니다.",
        )

        st.divider()

        # ── 데이터 내보내기 ───────────────────────────────────────
        st.markdown("**⬇️ 데이터 내보내기**")

        if df is not None and len(df) > 0:
            csv_bytes = df.to_csv(index=False).encode("utf-8-sig")
            st.download_button(
                "⬇️  정제된 데이터 CSV 다운로드",
                data=csv_bytes,
                file_name="pureset_cleaned.csv",
                mime="text/csv",
                use_container_width=True,
            )
        else:
            st.caption("데이터가 없어 다운로드할 수 없습니다.")

        # ── 정제 리포트 다운로드 (audit_log ≥ 1건일 때만 활성화) ──
        audit_log: list[str] = st.session_state.get("audit_log", [])
        has_audit = len(audit_log) > 0

        if has_audit and metrics is not None:
            report_bytes = _build_report_txt(audit_log, metrics).encode("utf-8")
            st.download_button(
                "📄  정제 리포트 다운로드",
                data=report_bytes,
                file_name="pureset_audit_report.txt",
                mime="text/plain",
                use_container_width=True,
                help="지금까지의 정제 이력과 최종 신뢰도 점수를 TXT 파일로 저장합니다.",
            )
        else:
            st.button(
                "📄  정제 리포트 다운로드",
                disabled=True,
                use_container_width=True,
                help="정제 작업을 1회 이상 실행하면 활성화됩니다.",
            )

        st.divider()

        # ── 상태 요약 ─────────────────────────────────────────────
        n_rows = len(df) if df is not None else 0
        st.caption(f"현재 행 수: **{n_rows:,}건**")
        if has_history:
            st.caption(f"롤백 가능: **{history_len}단계**")
        if has_audit:
            st.caption(f"정제 이력: **{len(audit_log)}건** 기록됨")
